# Generated by Django 5.1.1 on 2024-09-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_firestation_hospital'),
        ('users', '0004_customuser_civil_id_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficerPoliceStaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.policestation')),
            ],
        ),
    ]
