# Generated by Django 5.1.1 on 2024-09-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_policeofficerpolicestaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeofficerpolicestaion',
            old_name='officer',
            new_name='user',
        ),
    ]
