# Generated by Django 5.1.1 on 2024-09-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_firestation_hospital'),
        ('users', '0006_rename_officer_policeofficerpolicestaion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('user_lat', models.FloatField()),
                ('user_long', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_long', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('type_choice', models.CharField(choices=[('ambulance', 'Ambulance'), ('rescue', 'Rescue')], max_length=50)),
                ('attend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Police', to=settings.AUTH_USER_MODEL)),
                ('police_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.policestation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
