# Generated by Django 5.1.1 on 2024-09-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('USER', 'USER'), ('POLICE', 'POLICE')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attend_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Police', to=settings.AUTH_USER_MODEL),
        ),
    ]
