# Generated by Django 5.1.1 on 2024-09-12 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_gender_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attend_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POLICE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USER', to=settings.AUTH_USER_MODEL),
        ),
    ]
