# Generated by Django 5.1.1 on 2024-09-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_ticket_attend_id_alter_ticket_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
