# Generated by Django 5.1.1 on 2024-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ticket_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='distance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_choice',
            field=models.CharField(choices=[('AMBULANCE', 'AMBULANCE'), ('RESCUE', 'RESCUE')], max_length=50),
        ),
    ]
