# Generated by Django 5.1.1 on 2024-09-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_firestation_hospital'),
        ('users', '0011_alter_ticket_distance_alter_ticket_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='firetruck_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.firestation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.hospital'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_choice',
            field=models.CharField(choices=[('AMBULANCE', 'AMBULANCE'), ('FIRETRUCK', 'FIRETRUCK'), ('ACCIDENT', 'ACCIDENT')], max_length=50),
        ),
    ]
