# Generated by Django 5.1.1 on 2024-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_ticket_police_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fire_station_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='police_station_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
