# Generated by Django 4.2.16 on 2024-09-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0002_firestation_hospital"),
        ("users", "0014_ticket_fire_station_name_ticket_hospital_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cancel",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reason",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="policeofficerpolicestaion",
            name="police_station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.policestation",
            ),
        ),
    ]
