# Generated by Django 4.2.16 on 2024-09-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_policeofficerpolicestaion_police_station'),
        ('users', '0015_ticket_cancel_ticket_reason_and_more'),
    ]

    operations = [
    ]
