# Generated by Django 4.2.16 on 2024-09-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_ticket_created_at_ticket_gender_ticket_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
    ]
